### ISSUE TITLE
Problem with Circular imports

### ISSUE THREAD

**Issue by axgort** [EcmaXp/wfapi#4]
>>> import wfapi
Traceback (most recent call last):                                                                                                      
  File "<stdin>", line 1, in <module>                                                                                                   
  File "/home/havk/.virtualenvs/wfcli/src/wfapi/wfapi/__init__.py", line 7, in <module>                                                 
    from .workflowy import Workflowy                                                                                                    
  File "/home/havk/.virtualenvs/wfcli/src/wfapi/wfapi/workflowy.py", line 10, in <module>                                               
    from .base import BaseWorkflowy                                                                                                     
  File "/home/havk/.virtualenvs/wfcli/src/wfapi/wfapi/base.py", line 4, in <module>                                                     
    from wfapi.browser import get_default_workflowy_url                                                                                 
  File "/home/havk/.virtualenvs/wfcli/src/wfapi/wfapi/browser.py", line 12, in <module>                                                 
    from .base import BaseBrowser                                                                                                       
ImportError: cannot import name 'BaseBrowser'

**Comment by EcmaXp** [comment]
i think my package are broken

**Comment by EcmaXp** [comment]
https://github.com/EcmaXp/wfapi/commit/bf983a1df4126ca87ee4f4eeca50fa7954a4c41a are commited.

context-based operation are not working after 0.5.0a0
